// Auto-generated by the generator
// Don't manually edit this file

// @flow

import { increaseValue } from './increaseValue'
import { decreaseValue } from './decreaseValue'

export const buttonActions = {
  increaseValue,
  decreaseValue,
}
