// Auto-generated by the generator
// Don't manually edit this file

import { createStore, applyMiddleware, compose, combineReducers } from 'redux'
import createSagaMiddleware from 'redux-saga'
// import {router5Middleware as createRouterMiddleware, router5Reducer} from 'redux-router5'
import { router } from '../router'
import { initialState } from './initialState'
import { buttonReducer } from './button/reducers'
import { buttonEffects } from './button/effects'

const sagaMiddleware = createSagaMiddleware()
// const routerMiddleware = createRouterMiddleware(router)

const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose

const store = createStore(
  combineReducers({
    // router: router5Reducer,
    button: buttonReducer,
  }),
  initialState,
  composeEnhancers(applyMiddleware(
    sagaMiddleware, 
    // routerMiddleware
  ))
)

buttonEffects.forEach(fx => sagaMiddleware.run(fx))

export {
  store
}
