// Auto-generated by the generator
// Don't manually edit this file

// @flow

import { increamentEffect } from './increament'
import { decrementEffect } from './decrement'

export const buttonEffects = [
  increamentEffect,
  decrementEffect,
]
